source 'https://rubygems.org'
gem 'hyper-spec', path: '../hyper-spec'
gem 'rack', '< 3'  # puma <= 5.4 requires rack < 3 (rack/handler removed in rack 3)
# gem 'opal-browser', git: 'https://github.com/opal/opal-browser'
gemspec
